In [51]:
import fitz
import pandas as pd
import io
import glob
import re

In [52]:
all_pdf = glob.glob(r'pdfFiles/*.pdf')

In [53]:
len(all_pdf)

50

In [54]:
all_pdf

['pdfFiles/Современный Gradle для Java-разработчика_ один модуль — хорошо, несколько — лучше _ Хабр.pdf',
 'pdfFiles/Изменения в политике бесплатного лицензирования PVS-Studio _ Хабр.pdf',
 'pdfFiles/Как работают сборщики мусора, оцениваем Netflix и хейтеров _ Spring АйО Подкаст №37 _ Хабр.pdf',
 'pdfFiles/Veai на Heisenbug Spring и JPoint 2026 _ Хабр.pdf',
 'pdfFiles/18 сентября проведем Naumen Java Junior Meetup #3 для начинающих разработчиков _ Хабр.pdf',
 'pdfFiles/Синхронная Kafka, не используй Spring Security, ООП — зло _ Spring АйО Подкаст №30 _ Хабр.pdf',
 'pdfFiles/Почему код становится legacy_ _ Хабр.pdf',
 'pdfFiles/Представлен проект «Мобильные JAVA игры в Telegram» _ Хабр.pdf',
 'pdfFiles/Java&Kotlin-митап от MWS Cloud Platform в Казани _ Хабр.pdf',
 'pdfFiles/Приглашаем на Java-митап от Мир Plat.Form в Москве _ Хабр.pdf',
 'pdfFiles/Проект Minecraft_ Java Edition перейдёт на графический движок Vulkan _ Хабр.pdf',
 'pdfFiles/Вышла Java 25 _ Хабр.pdf',
 'pdfFiles/x86 больше не нужен, процессоры Amazon, параллельные стримы в Java _ Spring АйО Подкаст №53 _ Хабр.pdf',
 'pdfFiles/Статус Java 2026_ помогаем собрать актуальную картину по Java в России _ Хабр.pdf',
 'pdfFiles/Курс «Разработка мобильных игр» — успейте подать заявку до 25 января _ Хабр.pdf',
 'pdfFiles/Бесконечные циклы — зло, ИИ генерит мусор, LSP API для людей _ Spring АйО Подкаст №34 _ Хабр.pdf',
 'pdfFiles/Удаленная IDE, живы ли HTTP-клиенты в Spring, Java-геддон _ Spring АйО Подкаст №38 _ Хабр.pdf',
 'pdfFiles/Платформа доверенных сервисов «Росатома» получила крупное обновление _ Хабр.pdf',
 'pdfFiles/Не пиши на JavaScript, AWS не сдюжил, HTTP_3 не панацея _ Spring АйО Подкаст №40 _ Хабр.pdf',
 'pdfFiles/Приглашаем школьников на Mobile GameDev Bootcamp 2025 _ Хабр.pdf',
 'pdfFiles/Вышел Spring Framework 7.0 _ Хабр.pdf',
 'pdfFiles/Вебинар «От кода до запуска_ российский стек для Java — Axiom JDK и OpenIDE» _ Хабр.pdf',
 'pdfFiles/Карты, деньги, JVM _ Хабр.pdf',
 'pdfFiles/PVS-Studio 7.41_ MISRA C 2023, улучшения в работе с Unreal Engine, внедрение системы логирования и многое другое _ Хабр.pdf',
 'pdfFiles/Spring Boot 4 и Spring Framework 7, StableValue в Java, Postgres стал быстрее _ Spring АйО Подкаст №33 _ Хабр.pdf',
 'pdfFiles/IntelliJ IDEA переходит на единый дистрибутив, Rich Errors в Kotlin _ Spring АйО Подкаст №27 _ Хабр.pdf',
 'pdfFiles/Импорт HTTP-скриптов и приватное окружение_ релиз Amplicode 2025.3.2 _ Хабр.pdf',
 'pdfFiles/Вебинар «Вайб-кодинг в энтерпрайз_ 5 блокеров и путь к управляемой разработке» _ Хабр.pdf',
 'pdfFiles/Зачем нам Gradle 9, чем хорош Postgres 18 и секреты хорошего доклада _ Spring АйО Подкаст №36 _ Хабр.pdf',
 'pdfFiles/Новинки и перфоманс Java 25, паттерны и составные айдишники _ Spring АйО Подкаст №28 _ Хабр.pdf',
 'pdfFiles/Релиз Android-клавиатуры Unexpected Keyboard 2.0.0 _ Хабр.pdf',
 'pdfFiles/Встречаем Spring 7.0, оцениваем Jakarta Data, Quarkus казнить _ Spring АйО Подкаст №31 _ Хабр.pdf',
 'pdfFiles/IDEA 2025.3. Зависание в Maven проектах _ Хабр.pdf',
 'pdfFiles/TechRadar для Java-разработчиков возвращается _ Хабр.pdf',
 'pdfFiles/Spring Data JDBC – идеальная Data для вашего приложения _ Хабр.pdf',
 'pdfFiles/54 минуты с Михаилом Поливахой _ Spring АйО Подкаст №29 _ Хабр.pdf',
 'pdfFiles/Сбер выкатил GigaIDE 2025.1 _ Хабр.pdf',
 'pdfFiles/Вебинар «Повышение безопасности приложений с применением искусственного интеллекта» _ Хабр.pdf',
 'pdfFiles/Поддержка Python и JavaScript в рамках Spring Framework _ Хабр.pdf',
 'pdfFiles/В OpenIDE появился импорт настроек из JetBrains IDE и VS Code при первом запуске _ Хабр.pdf',
 'pdfFiles/GitHub опубликовал ежегодный статистический отчет _ Хабр.pdf',
 'pdfFiles/Объектно ориентированное програмирование в графических языках _ Хабр.pdf',
 'pdfFiles/Вебинар «Организация управления зависимостями в корпоративной разработке на примере Axiom Spring» _ Хабр.pdf',
 'pdfFiles/Вебинар «Управляемые обновления и безопасная цепочка поставок с Axiom JDK и Ginc» _ Хабр.pdf',
 'pdfFiles/Connekt_ Новый HTTP-клиент для IntelliJ IDEA — теперь Open Source _ Хабр.pdf',
 'pdfFiles/Fullstack проект на React, Python, Go и Spring_ OpenIDE в действии [видео] _ Хабр.pdf',
 'pdfFiles/Quarkus, профайлеры и коварный java.time_ Я.Субботник по JVM‑языкам _ Хабр.pdf',
 'pdfFiles/Вышел Spring Boot 4 _ Хабр.pdf',
 'pdfFiles/Copyright умер, AI против GPL, модели консистентности _ Spring АйО Подкаст №54 _ Хабр.pdf',
 'pdfFiles/JetBrains закрывает Fleet _ Хабр.pdf']

In [55]:
pdf_document = r"pdfFiles/Объектно ориентированное програмирование в графических языках _ Хабр.pdf"
doc = fitz.open(pdf_document)
print("Исходный документ: ", doc)
print("\nКоличество страниц: %i\n\n------------------\n\n" % doc.page_count)
for current_page in range(2):
    page = doc.load_page(current_page)
    page_text = page.get_text("text")
    print("Стр. ", current_page+1, "\n")
    print(page_text)

Исходный документ:  Document('pdfFiles/Объектно ориентированное програмирование в графических языках _ Хабр.pdf')

Количество страниц: 17

------------------


Стр.  1

Объектно-ориентированное программирование (ООП) – концепция, которая призвана облегчить
разработку сложных систем, за счет введения новых понятий, более приближенных к реальному
миру, чем функциональные и процедурные языки программирования. Как пишет википедия,
«Обычный человеческий язык в целом отражает идеологию ООП, начиная с инкапсуляции
представления о предмете в виде его имени и заканчивая полиморфизмом использования слова в
переносном смысле, что в итоге развивает выражение представления через имя предмета до
полноценного понятия – класса.»
Но с точки зрения всех, кто впервые сталкивался эти этим абстракциями, после классических
процедурных языков понятнее не становилось, кажется наоборот все еще больше запутывалось.
С другой стороны, есть графические нотации работы программы, которые не приближены к
человеческому языку, но гораздо понятнее, чем даже любой код, не то что ООП. Вполне возможно,
что это более понятно мне, испорченному инженерным образованием, но таких как я много и этот
petuhoff
13 мая 2019 в 16:52
Объектно ориентированное програмирование в графических
языках
7 мин
17K
SCADA*, Анализ и проектирование систем*, Графические оболочки*, ООП*, Промышленное программирование*
РЕКЛАМА
Вложение в навыки
Лучшая стратегия в кризис
РЕКЛАМА
Проложите ребенку путь в ИТ
Объектно ориентированное програмирование в графи...
https://habr.com/ru/articles/451148/
1 of 17
5/13/26, 20:34

Стр.  2

текст для таких же испорченных физиков, не понимающих высокие абстракции.
Вот, например, реальное описание в графической нотации алгоритма управления задвижками
АЭС.:
Рисунок 1. Пример программы управления АЭС в графической нотации
Слева входные сигналы, справа команды.
Мне кажется, что такой алгоритм прочитать может даже ребенок:
• Если насос включен в течении 60 секунд и расход меньше 10, то задвижку на рециркуляции
открыть.
• Если насос включен, то подавать в течении 5 секунд на задвижки 001 и 002 команду открыть.
• Если расход больше 20 и насос включен, то в течении 5 секунд на задвижку 003 подавать
команду закрыть.
В бытность мою студентом я подрабатывал, создавая библиотеку компонентов для Delphi и был
знаком с ООП не понаслышке. Потом, когда столкнулся с реальными программами управления
АЭС, очень удивился что нет никакого абстрагирования, инкапсуляции и, прости господи
полиморфизма, только чистый Си, и еще желательно урезанный правилами и рекомендация
MISRA C, чтобы все было надёжно, переносимо, безопасно.
Вершиной обрезания Си в моей практике был язык FIL, для систем управления реакторами РБМК.
В нем функции заранее писались на Си, компилировались, а потом вызывались на основе
текстового файла, где они были описаны на языке FIL. В итоге, можно было вызвать только
ограниченный, но тщательно проверенный и отлаженный набор функций. И все это – во имя
безопасности и надежности.
Но при этом система управления реактором и в целом система управления АЭС – это как раз тот
случай, где принципы ООП должны применятся в полный рост. В само деле, есть множество
однотипного оборудования – задвижки, насосы, датчики, всё легко классифицируется, есть готовые
объекты, соответствующие реальному оборудованию. Казалось бы, вот оно – применяй ООП,
классы, наследование, абстрагирование и полиморфизм. Но нет, нужен чистый Си и это
требования безопасности.
А дальше – еще интереснее. На самом деле программу для управления АЭС пишет не
программист, а технолог – только он знает, что и когда закрывать, открывать, включать, а главное –
он знает, когда всю это байду выключать, чтобы не долбануло. А программист должен аккуратно
всё это реализовать на коде Си. А еще лучше, что бы программиста вообще бы не было, а
технолог сам рисовал технологические алгоритмы управляющих программ в графическом виде,
Вложение в навыки
Лучшая стратегия в кризис
РЕКЛАМА
Объектно ориентированное програмирование в графи...
https://habr.com/ru/articles/451148/
2 of 17
5/13/26, 20:34

In [56]:
def parse_habr_article(text):
    """Парсит статью с Хабра по структуре внизу страницы"""
    lines = text.split('\n')
    result = {
        'author': '',
        'date': '',
        'title': '',
        'read_time': '',
        'views': '',
        'tags': ''
    }
    
    for i, line in enumerate(lines):
        if re.match(r'^[a-z0-9\-]+$', line.strip(), re.I):
            result['author'] = line.strip()
            
            # Следующая строка дата
            if i + 1 < len(lines):
                result['date'] = lines[i + 1].strip()
            
            # Через 1-2 строки заголовок
            if i + 2 < len(lines):
                result['title'] = lines[i + 2].strip()
            
            # Ещё через 1-2 строки время чтения
            if i + 3 < len(lines):
                time_match = re.search(r'(\d+\s*мин)', lines[i + 3])
                if time_match:
                    result['read_time'] = time_match.group(1)
            
            # Просмотры через строку после времени
            if i + 4 < len(lines):
                views_match = re.search(r'(\d+(?:\.\d+)?[KМ])', lines[i + 4])
                if views_match:
                    result['views'] = views_match.group(1)
            
            # Теги в следующей строке с символами * 
            if i + 5 < len(lines) and '*' in lines[i + 5]:
                result['tags'] = lines[i + 5].strip()
            
            break
    
    return result

In [57]:
for pdf_path in all_pdf:
    doc = fitz.open(pdf_path)
    first_page = doc[0].get_text("text")
    data = parse_habr_article(first_page)
    print(f"\n=== {pdf_path.split('/')[-1]} ===")
    print(f"Автор: {data['author']}")
    print(f"Дата: {data['date']}")
    print(f"Заголовок: {data['title']}")
    print(f"Время: {data['read_time']}")
    print(f"Просмотры: {data['views']}")
    doc.close()

=== Современный Gradle для Java-разработчика_ один модуль — хорошо, несколько — лучше _ Хабр.pdf ===
Автор: PVS-Studio
Дата: 200,63 Рейтинг
Заголовок: 93 781 Подписчики
Время:
Просмотры:

=== Изменения в политике бесплатного лицензирования PVS-Studio _ Хабр.pdf ===
Автор: PVS-Studio
Дата: 200,63 Рейтинг
Заголовок: 93 781 Подписчики
Время:
Просмотры:

=== Как работают сборщики мусора, оцениваем Netflix и хейтеров _ Spring АйО Подкаст №37 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== Veai на Heisenbug Spring и JPoint 2026 _ Хабр.pdf ===
Автор: Veai
Дата: 97,64 Рейтинг
Заголовок: 71 Подписчики
Время:
Просмотры:

=== 18 сентября проведем Naumen Java Junior Meetup #3 для начинающих разработчиков _ Хабр.pdf ===
Автор: NAUMEN
Дата: 73,15 Рейтинг
Заголовок: 509 Подписчики
Время:
Просмотры:

=== Синхронная Kafka, не используй Spring Security, ООП — зло _ Spring АйО Подкаст №30 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== Почему код становится legacy_ _ Хабр.pdf ===
Автор: kino6052
Дата: 31 авг 2023 в 16:01
Заголовок: Почему код становится legacy?
Время: 7 мин
Просмотры: 14K

=== Представлен проект «Мобильные JAVA игры в Telegram» _ Хабр.pdf ===
Автор: denis-19
Дата: 21 окт 2025 в 21:10
Заголовок: Представлен проект «Мобильные JAVA игры в Telegram»
Время: 2 мин
Просмотры: 15K

=== Java&Kotlin-митап от MWS Cloud Platform в Казани _ Хабр.pdf ===
Автор: MTCWebServices
Дата: 3 сен 2025 в 13:00
Заголовок: Java&Kotlin-митап от MWS Cloud Platform в Казани
Время: 1 мин
Просмотры: 3.3K

=== Приглашаем на Java-митап от Мир Plat.Form в Москве _ Хабр.pdf ===
Автор: vwisty
Дата: 25 ноя 2025 в 15:27
Заголовок: Приглашаем на Java-митап от Мир Plat.Form в Москве
Время: 2 мин
Просмотры: 3.8K

=== Проект Minecraft_ Java Edition перейдёт на графический движок Vulkan _ Хабр.pdf ===
Автор: Vulkan
Дата: 2 мин
Заголовок: 12K
Время:
Просмотры:

=== Вышла Java 25 _ Хабр.pdf ===
Автор: orionll
Дата: 16 сен 2025 в 19:30
Заголовок: Вышла Java 25
Время: 21 мин
Просмотры: 44K

=== x86 больше не нужен, процессоры Amazon, параллельные стримы в Java _ Spring АйО Подкаст №53 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== Статус Java 2026_ помогаем собрать актуальную картину по Java в России _ Хабр.pdf ===
Автор: alexbik
Дата: 7 апр в 17:30
Заголовок: Статус Java 2026: помогаем собрать актуальную картину по Java в
Время:
Просмотры:

=== Курс «Разработка мобильных игр» — успейте подать заявку до 25 января _ Хабр.pdf ===
Автор: Samsung
Дата: 64,54 Рейтинг
Заголовок: 38 733 Подписчики
Время:
Просмотры:

=== Бесконечные циклы — зло, ИИ генерит мусор, LSP API для людей _ Spring АйО Подкаст №34 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== Удаленная IDE, живы ли HTTP-клиенты в Spring, Java-геддон _ Spring АйО Подкаст №38 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== Платформа доверенных сервисов «Росатома» получила крупное обновление _ Хабр.pdf ===
Автор: 4K
Дата: Блог компании ITFB Group, Криптография*, PostgreSQL*, VueJS*, Java*
Заголовок: РЕКЛАМА
Время:
Просмотры:

=== Не пиши на JavaScript, AWS не сдюжил, HTTP_3 не панацея _ Spring АйО Подкаст №40 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== Приглашаем школьников на Mobile GameDev Bootcamp 2025 _ Хабр.pdf ===
Автор: Samsung
Дата: 64,54 Рейтинг
Заголовок: 38 733 Подписчики
Время:
Просмотры:

=== Вышел Spring Framework 7.0 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== Вебинар «От кода до запуска_ российский стек для Java — Axiom JDK и OpenIDE» _ Хабр.pdf ===
Автор: ekhala
Дата: 15 авг 2025 в 12:00
Заголовок: Вебинар «От кода до запуска: российский стек для Java — Axiom
Время:
Просмотры:

=== Карты, деньги, JVM _ Хабр.pdf ===
Автор: PVS-Studio
Дата: 200,63 Рейтинг
Заголовок: 93 781 Подписчики
Время:
Просмотры:

=== PVS-Studio 7.41_ MISRA C 2023, улучшения в работе с Unreal Engine, внедрение системы логирования и многое другое _ Хабр.pdf ===
Автор: PVS-Studio
Дата: 200,63 Рейтинг
Заголовок: 93 781 Подписчики
Время:
Просмотры:

=== Spring Boot 4 и Spring Framework 7, StableValue в Java, Postgres стал быстрее _ Spring АйО Подкаст №33 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== IntelliJ IDEA переходит на единый дистрибутив, Rich Errors в Kotlin _ Spring АйО Подкаст №27 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== Импорт HTTP-скриптов и приватное окружение_ релиз Amplicode 2025.3.2 _ Хабр.pdf ===
Автор: Haulmont
Дата: 146,22 Рейтинг
Заголовок: 84 880 Подписчики
Время:
Просмотры:

=== Вебинар «Вайб-кодинг в энтерпрайз_ 5 блокеров и путь к управляемой разработке» _ Хабр.pdf ===
Автор: Haulmont
Дата: 146,22 Рейтинг
Заголовок: 84 880 Подписчики
Время:
Просмотры:

=== Зачем нам Gradle 9, чем хорош Postgres 18 и секреты хорошего доклада _ Spring АйО Подкаст №36 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== Новинки и перфоманс Java 25, паттерны и составные айдишники _ Spring АйО Подкаст №28 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== Релиз Android-клавиатуры Unexpected Keyboard 2.0.0 _ Хабр.pdf ===
Автор: denis-19
Дата: 5 мая в 07:30
Заголовок: Релиз Android-клавиатуры Unexpected Keyboard 2.0.0
Время: 1 мин
Просмотры: 12K

=== Встречаем Spring 7.0, оцениваем Jakarta Data, Quarkus казнить _ Spring АйО Подкаст №31 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== IDEA 2025.3. Зависание в Maven проектах _ Хабр.pdf ===
Автор: Maven
Дата: По моему мнению п.2 можно пропустить. Главное удалить кэш и папку .idea. И далее просто не
Заголовок: использовать bundled Maven для открытия проектов. В форки GigaIDE & OpenIDE данная проблема
Время:
Просмотры:

=== TechRadar для Java-разработчиков возвращается _ Хабр.pdf ===
Автор: 8
Дата: 0
Заголовок: РЕКЛАМА
Время:
Просмотры:

=== Spring Data JDBC – идеальная Data для вашего приложения _ Хабр.pdf ===
Автор: Haulmont
Дата: 146,22 Рейтинг
Заголовок: 84 880 Подписчики
Время:
Просмотры:

=== 54 минуты с Михаилом Поливахой _ Spring АйО Подкаст №29 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== Сбер выкатил GigaIDE 2025.1 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== Вебинар «Повышение безопасности приложений с применением искусственного интеллекта» _ Хабр.pdf ===
Автор: ekhala
Дата: 26 фев в 17:10
Заголовок: Вебинар «Повышение безопасности приложений с применением
Время:
Просмотры:

=== Поддержка Python и JavaScript в рамках Spring Framework _ Хабр.pdf ===
Автор: mipo256
Дата: 25 ноя 2025 в 20:05
Заголовок: Поддержка Python и JavaScript в рамках Spring Framework
Время: 3 мин
Просмотры: 6.6K

=== В OpenIDE появился импорт настроек из JetBrains IDE и VS Code при первом запуске _ Хабр.pdf ===
Автор: Haulmont
Дата: 146,22 Рейтинг
Заголовок: 84 880 Подписчики
Время:
Просмотры:

=== GitHub опубликовал ежегодный статистический отчет _ Хабр.pdf ===
Автор: denis-19
Дата: 3 дек 2020 в 10:40
Заголовок: GitHub опубликовал ежегодный статистический отчет
Время: 2 мин
Просмотры: 6.2K

=== Объектно ориентированное програмирование в графических языках _ Хабр.pdf ===
Автор: petuhoff
Дата: 13 мая 2019 в 16:52
Заголовок: Объектно ориентированное програмирование в графических
Время:
Просмотры:

=== Вебинар «Организация управления зависимостями в корпоративной разработке на примере Axiom Spring» _ Хабр.pdf ===
Автор: ekhala
Дата: 12 апр в 12:00
Заголовок: Вебинар «Организация управления зависимостями в
Время:
Просмотры:

=== Вебинар «Управляемые обновления и безопасная цепочка поставок с Axiom JDK и Ginc» _ Хабр.pdf ===
Автор: ekhala
Дата: 13 мар в 14:20
Заголовок: Вебинар «Управляемые обновления и безопасная цепочка
Время:
Просмотры:

=== Connekt_ Новый HTTP-клиент для IntelliJ IDEA — теперь Open Source _ Хабр.pdf ===
Автор: Haulmont
Дата: 146,22 Рейтинг
Заголовок: 84 880 Подписчики
Время:
Просмотры:

=== Fullstack проект на React, Python, Go и Spring_ OpenIDE в действии [видео] _ Хабр.pdf ===
Автор: Haulmont
Дата: 146,22 Рейтинг
Заголовок: 84 880 Подписчики
Время:
Просмотры:

=== Quarkus, профайлеры и коварный java.time_ Я.Субботник по JVM‑языкам _ Хабр.pdf ===
Автор: NatalieVT
Дата: 16 мар в 14:00
Заголовок: Quarkus, профайлеры и коварный java.time: Я.Субботник
Время:
Просмотры:

=== Вышел Spring Boot 4 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== Copyright умер, AI против GPL, модели консистентности _ Spring АйО Подкаст №54 _ Хабр.pdf ===
Автор:
Дата:
Заголовок:
Время:
Просмотры:

=== JetBrains закрывает Fleet _ Хабр.pdf ===
Автор: 15K
Дата: Блог компании Spring АйО, Программирование*, Java*, Текстовые редакторы и IDE*
Заголовок: РЕКЛАМА
Время:
Просмотры:

In [60]:
def extract_text_from_pdf(pdf_path):
    """Извлекает весь текст из PDF постранично"""
    doc = fitz.open(pdf_path)
    text_pages = []
    for page_num in range(len(doc)):
        page = doc.load_page(page_num)
        text_pages.append(page.get_text("text"))
    doc.close()
    return text_pages

In [61]:
def has_author(text_content):
    """Проверяет, есть ли в тексте автор (никнейм)"""
    
    author_pattern = r'^[a-z0-9\-]+(?:\s+\d+\s+(?:час|мин|сек))?$'
    
    first_page = text_content[0] if text_content else ""
    lines = first_page.split('\n')
    
    for line in lines:
        line = line.strip()
        if re.match(author_pattern, line, re.IGNORECASE):
            if len(line) < 50 and not any(c in line for c in [' ', '.', ',', '!', '?']):
                return True
    return False

def has_minimal_content(text_content, min_chars=500):
    """Проверяет, что в PDF есть минимальный текст"""
    full_text = ' '.join(text_content)
    return len(full_text) > min_chars

In [63]:
# Очищенные списки
clean_pdfs = []
clean_names = []

filtered_NameCompany = []
filtered_Raiting = []
filtered_DataPublish = []
filtered_Activity = []
filtered_TextArticle = []

for pdf_path in all_pdf:
    try:
        text_content = extract_text_from_pdf(pdf_path)
        filename = pdf_path.split('/')[-1]
        
        # Проверяем наличие автора (через parse_habr_article)
        first_page = text_content[0] if text_content else ""
        parsed = parse_habr_article(first_page)
        
        # Автор считается найденным, если строка не пустая и не похожа на мусор
        has_valid_author = (
            parsed['author'] and 
            len(parsed['author']) > 1 and
            not parsed['author'].replace('.', '').isdigit() and
            parsed['author'] not in ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
        )
        
        # Проверяем минимальное содержимое
        full_text = ' '.join(text_content)
        has_content = len(full_text) > 500
        
        if has_valid_author and has_content:
            print(f"✓ ПОЛНЫЙ: {filename}")
            print(f"   Автор: {parsed['author']}, Заголовок: {parsed['title'][:50]}...")
            
            # Сохраняем данные
            filtered_NameCompany.append(parsed['author'])
            filtered_Raiting.append(parsed['views'])
            filtered_DataPublish.append(parsed['date'])
            filtered_Activity.append(parsed['tags'])
            filtered_TextArticle.append(full_text)
            clean_pdfs.append(pdf_path)
            clean_names.append(filename)
        else:
            if not has_valid_author:
                print(f"✗ НЕТ АВТОРА: {filename} (найдено: '{parsed['author']}')")
            elif not has_content:
                print(f"✗ ПУСТОЙ/КОРОТКИЙ: {filename}")
                
    except Exception as e:
        print(f"✗ ОШИБКА при чтении {pdf_path}: {e}")

print(f"\n\nИтого: {len(clean_pdfs)} полных PDF из {len(all_pdf)}")
print("Отфильтрованные файлы:", clean_names)

✓ ПОЛНЫЙ: Современный Gradle для Java-разработчика_ один модуль — хорошо, несколько — лучше _ Хабр.pdf
   Автор: PVS-Studio, Заголовок: 93 781 Подписчики...
✓ ПОЛНЫЙ: Изменения в политике бесплатного лицензирования PVS-Studio _ Хабр.pdf
   Автор: PVS-Studio, Заголовок: 93 781 Подписчики...
✗ НЕТ АВТОРА: Как работают сборщики мусора, оцениваем Netflix и хейтеров _ Spring АйО Подкаст №37 _ Хабр.pdf (найдено: '')
✓ ПОЛНЫЙ: Veai на Heisenbug Spring и JPoint 2026 _ Хабр.pdf
   Автор: Veai, Заголовок: 71 Подписчики...
✓ ПОЛНЫЙ: 18 сентября проведем Naumen Java Junior Meetup #3 для начинающих разработчиков _ Хабр.pdf
   Автор: NAUMEN, Заголовок: 509 Подписчики...
✗ НЕТ АВТОРА: Синхронная Kafka, не используй Spring Security, ООП — зло _ Spring АйО Подкаст №30 _ Хабр.pdf (найдено: '')
✓ ПОЛНЫЙ: Почему код становится legacy_ _ Хабр.pdf
   Автор: kino6052, Заголовок: Почему код становится legacy?...
✓ ПОЛНЫЙ: Представлен проект «Мобильные JAVA игры в Telegram» _ Хабр.pdf
   Автор: denis-19, Заголовок: Представлен проект «Мобильные JAVA игры в Telegram...
✓ ПОЛНЫЙ: Java&Kotlin-митап от MWS Cloud Platform в Казани _ Хабр.pdf
   Автор: MTCWebServices, Заголовок: Java&Kotlin-митап от MWS Cloud Platform в Казани...
✓ ПОЛНЫЙ: Приглашаем на Java-митап от Мир Plat.Form в Москве _ Хабр.pdf
   Автор: vwisty, Заголовок: Приглашаем на Java-митап от Мир Plat.Form в Москве...
✓ ПОЛНЫЙ: Проект Minecraft_ Java Edition перейдёт на графический движок Vulkan _ Хабр.pdf
   Автор: Vulkan, Заголовок: 12K...
✓ ПОЛНЫЙ: Вышла Java 25 _ Хабр.pdf
   Автор: orionll, Заголовок: Вышла Java 25...
✗ НЕТ АВТОРА: x86 больше не нужен, процессоры Amazon, параллельные стримы в Java _ Spring АйО Подкаст №53 _ Хабр.pdf (найдено: '')
✓ ПОЛНЫЙ: Статус Java 2026_ помогаем собрать актуальную картину по Java в России _ Хабр.pdf
   Автор: alexbik, Заголовок: Статус Java 2026: помогаем собрать актуальную карт...
✓ ПОЛНЫЙ: Курс «Разработка мобильных игр» — успейте подать заявку до 25 января _ Хабр.pdf
   Автор: Samsung, Заголовок: 38 733 Подписчики...
✗ НЕТ АВТОРА: Бесконечные циклы — зло, ИИ генерит мусор, LSP API для людей _ Spring АйО Подкаст №34 _ Хабр.pdf (найдено: '')
✗ НЕТ АВТОРА: Удаленная IDE, живы ли HTTP-клиенты в Spring, Java-геддон _ Spring АйО Подкаст №38 _ Хабр.pdf (найдено: '')
✓ ПОЛНЫЙ: Платформа доверенных сервисов «Росатома» получила крупное обновление _ Хабр.pdf
   Автор: 4K, Заголовок: РЕКЛАМА...
✗ НЕТ АВТОРА: Не пиши на JavaScript, AWS не сдюжил, HTTP_3 не панацея _ Spring АйО Подкаст №40 _ Хабр.pdf (найдено: '')
✓ ПОЛНЫЙ: Приглашаем школьников на Mobile GameDev Bootcamp 2025 _ Хабр.pdf
   Автор: Samsung, Заголовок: 38 733 Подписчики...
✗ НЕТ АВТОРА: Вышел Spring Framework 7.0 _ Хабр.pdf (найдено: '')
✓ ПОЛНЫЙ: Вебинар «От кода до запуска_ российский стек для Java — Axiom JDK и OpenIDE» _ Хабр.pdf
   Автор: ekhala, Заголовок: Вебинар «От кода до запуска: российский стек для J...
✓ ПОЛНЫЙ: Карты, деньги, JVM _ Хабр.pdf
   Автор: PVS-Studio, Заголовок: 93 781 Подписчики...
✓ ПОЛНЫЙ: PVS-Studio 7.41_ MISRA C 2023, улучшения в работе с Unreal Engine, внедрение системы логирования и многое другое _ Хабр.pdf
   Автор: PVS-Studio, Заголовок: 93 781 Подписчики...
✗ НЕТ АВТОРА: Spring Boot 4 и Spring Framework 7, StableValue в Java, Postgres стал быстрее _ Spring АйО Подкаст №33 _ Хабр.pdf (найдено: '')
✗ НЕТ АВТОРА: IntelliJ IDEA переходит на единый дистрибутив, Rich Errors в Kotlin _ Spring АйО Подкаст №27 _ Хабр.pdf (найдено: '')
✓ ПОЛНЫЙ: Импорт HTTP-скриптов и приватное окружение_ релиз Amplicode 2025.3.2 _ Хабр.pdf
   Автор: Haulmont, Заголовок: 84 880 Подписчики...
✓ ПОЛНЫЙ: Вебинар «Вайб-кодинг в энтерпрайз_ 5 блокеров и путь к управляемой разработке» _ Хабр.pdf
   Автор: Haulmont, Заголовок: 84 880 Подписчики...
✗ НЕТ АВТОРА: Зачем нам Gradle 9, чем хорош Postgres 18 и секреты хорошего доклада _ Spring АйО Подкаст №36 _ Хабр.pdf (найдено: '')
✗ НЕТ АВТОРА: Новинки и перфоманс Java 25, паттерны и составные айдишники _ Spring АйО Подкаст №28 _ Хабр.pdf (найдено: '')
✓ ПОЛНЫЙ: Релиз Android-клавиатуры Unexpected Keyboard 2.0.0 _ Хабр.pdf
   Автор: denis-19, Заголовок: Релиз Android-клавиатуры Unexpected Keyboard 2.0.0...
✗ НЕТ АВТОРА: Встречаем Spring 7.0, оцениваем Jakarta Data, Quarkus казнить _ Spring АйО Подкаст №31 _ Хабр.pdf (найдено: '')
✓ ПОЛНЫЙ: IDEA 2025.3. Зависание в Maven проектах _ Хабр.pdf
   Автор: Maven, Заголовок: использовать bundled Maven для открытия проектов. ...
✗ НЕТ АВТОРА: TechRadar для Java-разработчиков возвращается _ Хабр.pdf (найдено: '8')
✓ ПОЛНЫЙ: Spring Data JDBC – идеальная Data для вашего приложения _ Хабр.pdf
   Автор: Haulmont, Заголовок: 84 880 Подписчики...
✗ НЕТ АВТОРА: 54 минуты с Михаилом Поливахой _ Spring АйО Подкаст №29 _ Хабр.pdf (найдено: '')
✗ НЕТ АВТОРА: Сбер выкатил GigaIDE 2025.1 _ Хабр.pdf (найдено: '')
✓ ПОЛНЫЙ: Вебинар «Повышение безопасности приложений с применением искусственного интеллекта» _ Хабр.pdf
   Автор: ekhala, Заголовок: Вебинар «Повышение безопасности приложений с приме...
✓ ПОЛНЫЙ: Поддержка Python и JavaScript в рамках Spring Framework _ Хабр.pdf
   Автор: mipo256, Заголовок: Поддержка Python и JavaScript в рамках Spring Fram...
✓ ПОЛНЫЙ: В OpenIDE появился импорт настроек из JetBrains IDE и VS Code при первом запуске _ Хабр.pdf
   Автор: Haulmont, Заголовок: 84 880 Подписчики...
✓ ПОЛНЫЙ: GitHub опубликовал ежегодный статистический отчет _ Хабр.pdf
   Автор: denis-19, Заголовок: GitHub опубликовал ежегодный статистический отчет...
✓ ПОЛНЫЙ: Объектно ориентированное програмирование в графических языках _ Хабр.pdf
   Автор: petuhoff, Заголовок: Объектно ориентированное програмирование в графиче...
✓ ПОЛНЫЙ: Вебинар «Организация управления зависимостями в корпоративной разработке на примере Axiom Spring» _ Хабр.pdf
   Автор: ekhala, Заголовок: Вебинар «Организация управления зависимостями в...
✓ ПОЛНЫЙ: Вебинар «Управляемые обновления и безопасная цепочка поставок с Axiom JDK и Ginc» _ Хабр.pdf
   Автор: ekhala, Заголовок: Вебинар «Управляемые обновления и безопасная цепоч...
✓ ПОЛНЫЙ: Connekt_ Новый HTTP-клиент для IntelliJ IDEA — теперь Open Source _ Хабр.pdf
   Автор: Haulmont, Заголовок: 84 880 Подписчики...
✓ ПОЛНЫЙ: Fullstack проект на React, Python, Go и Spring_ OpenIDE в действии [видео] _ Хабр.pdf
   Автор: Haulmont, Заголовок: 84 880 Подписчики...
✓ ПОЛНЫЙ: Quarkus, профайлеры и коварный java.time_ Я.Субботник по JVM‑языкам _ Хабр.pdf
   Автор: NatalieVT, Заголовок: Quarkus, профайлеры и коварный java.time: Я.Суббот...
✗ НЕТ АВТОРА: Вышел Spring Boot 4 _ Хабр.pdf (найдено: '')
✗ НЕТ АВТОРА: Copyright умер, AI против GPL, модели консистентности _ Spring АйО Подкаст №54 _ Хабр.pdf (найдено: '')
✓ ПОЛНЫЙ: JetBrains закрывает Fleet _ Хабр.pdf
   Автор: 15K, Заголовок: РЕКЛАМА...


Итого: 33 полных PDF из 50
Отфильтрованные файлы: ['Современный Gradle для Java-разработчика_ один модуль — хорошо, несколько — лучше _ Хабр.pdf', 'Изменения в политике бесплатного лицензирования PVS-Studio _ Хабр.pdf', 'Veai на Heisenbug Spring и JPoint 2026 _ Хабр.pdf', '18 сентября проведем Naumen Java Junior Meetup #3 для начинающих разработчиков _ Хабр.pdf', 'Почему код становится legacy_ _ Хабр.pdf', 'Представлен проект «Мобильные JAVA игры в Telegram» _ Хабр.pdf', 'Java&Kotlin-митап от MWS Cloud Platform в Казани _ Хабр.pdf', 'Приглашаем на Java-митап от Мир Plat.Form в Москве _ Хабр.pdf', 'Проект Minecraft_ Java Edition перейдёт на графический движок Vulkan _ Хабр.pdf', 'Вышла Java 25 _ Хабр.pdf', 'Статус Java 2026_ помогаем собрать актуальную картину по Java в России _ Хабр.pdf', 'Курс «Разработка мобильных игр» — успейте подать заявку до 25 января _ Хабр.pdf', 'Платформа доверенных сервисов «Росатома» получила крупное обновление _ Хабр.pdf', 'Приглашаем школьников на Mobile GameDev Bootcamp 2025 _ Хабр.pdf', 'Вебинар «От кода до запуска_ российский стек для Java — Axiom JDK и OpenIDE» _ Хабр.pdf', 'Карты, деньги, JVM _ Хабр.pdf', 'PVS-Studio 7.41_ MISRA C 2023, улучшения в работе с Unreal Engine, внедрение системы логирования и многое другое _ Хабр.pdf', 'Импорт HTTP-скриптов и приватное окружение_ релиз Amplicode 2025.3.2 _ Хабр.pdf', 'Вебинар «Вайб-кодинг в энтерпрайз_ 5 блокеров и путь к управляемой разработке» _ Хабр.pdf', 'Релиз Android-клавиатуры Unexpected Keyboard 2.0.0 _ Хабр.pdf', 'IDEA 2025.3. Зависание в Maven проектах _ Хабр.pdf', 'Spring Data JDBC – идеальная Data для вашего приложения _ Хабр.pdf', 'Вебинар «Повышение безопасности приложений с применением искусственного интеллекта» _ Хабр.pdf', 'Поддержка Python и JavaScript в рамках Spring Framework _ Хабр.pdf', 'В OpenIDE появился импорт настроек из JetBrains IDE и VS Code при первом запуске _ Хабр.pdf', 'GitHub опубликовал ежегодный статистический отчет _ Хабр.pdf', 'Объектно ориентированное програмирование в графических языках _ Хабр.pdf', 'Вебинар «Организация управления зависимостями в корпоративной разработке на примере Axiom Spring» _ Хабр.pdf', 'Вебинар «Управляемые обновления и безопасная цепочка поставок с Axiom JDK и Ginc» _ Хабр.pdf', 'Connekt_ Новый HTTP-клиент для IntelliJ IDEA — теперь Open Source _ Хабр.pdf', 'Fullstack проект на React, Python, Go и Spring_ OpenIDE в действии [видео] _ Хабр.pdf', 'Quarkus, профайлеры и коварный java.time_ Я.Субботник по JVM‑языкам _ Хабр.pdf', 'JetBrains закрывает Fleet _ Хабр.pdf']

In [64]:
if len(clean_names) > 0:
    clean_df = pd.DataFrame({
        'Author': filtered_NameCompany,
        'Views': filtered_Raiting,
        'Date': filtered_DataPublish,
        'Tags': filtered_Activity,
        'Text': filtered_TextArticle,
        'Filename': clean_names,
        'Path': clean_pdfs
    })
    
    print(f"\nСоздан DataFrame с {len(clean_df)} записями")
    display(clean_df.head())
    
    clean_df.to_csv(r"clean_habr_articles.csv", index=False)
    print("Сохранено в clean_habr_articles.csv")
else:
    print("Нет полных PDF для сохранения")

Создан DataFrame с 33 записями

,Author,Views,Date,Tags,Text,Filename,Path
0,PVS-Studio,,"200,63 Рейтинг",,"64K+\nОхват за 30 дней\nPVS-Studio\n200,63 Рей...",Современный Gradle для Java-разработчика_ один...,pdfFiles/Современный Gradle для Java-разработч...
1,PVS-Studio,,"200,63 Рейтинг",,"64K+\nОхват за 30 дней\nPVS-Studio\n200,63 Рей...",Изменения в политике бесплатного лицензировани...,pdfFiles/Изменения в политике бесплатного лице...
2,Veai,,"97,64 Рейтинг",,"64K+\nОхват за 30 дней\nVeai\n97,64 Рейтинг\n7...",Veai на Heisenbug Spring и JPoint 2026 _ Хабр.pdf,pdfFiles/Veai на Heisenbug Spring и JPoint 202...
3,NAUMEN,,"73,15 Рейтинг",,"8K+\nОхват за 30 дней\nNAUMEN\n73,15 Рейтинг\n...",18 сентября проведем Naumen Java Junior Meetup...,pdfFiles/18 сентября проведем Naumen Java Juni...
4,kino6052,14K,31 авг 2023 в 16:01,"Блог компании билайн, Программирование*, Качес...","2K+\nОхват за 30 дней\nбилайн\n60,12 Рейтинг\n...",Почему код становится legacy_ _ Хабр.pdf,pdfFiles/Почему код становится legacy_ _ Хабр.pdf

Сохранено в clean_habr_articles.csv

In [66]:
df = pd.DataFrame({
    'NameCompany': [],
    'Description': [],
    'Raiting': [],
    'DataPublish': [],
    'Activity': [],
    'TextArticle': [] 
})

for pdf_path in clean_pdfs:
    try:
        text_content = extract_text_from_pdf(pdf_path)
        first_page = text_content[0] if text_content else ""
        
        parsed = parse_habr_article(first_page)
        
        full_text = ' '.join(text_content).replace('\n', ' ').strip()
        
        new_row = pd.DataFrame({
            'NameCompany': [parsed['author']],
            'Description': [parsed['title']],
            'Raiting': [parsed['views']],
            'DataPublish': [parsed['date']],
            'Activity': [parsed['tags']],
            'TextArticle': [full_text]
        })
        
        df = pd.concat([df, new_row], ignore_index=True)
        
    except Exception as e:
        print(f"Ошибка при обработке {pdf_path}: {e}")

print(f"Создан DataFrame с {len(df)} записями")
df.head(30)

Создан DataFrame с 33 записями

,NameCompany,Description,Raiting,DataPublish,Activity,TextArticle
0,PVS-Studio,93 781 Подписчики,,"200,63 Рейтинг",,"64K+ Охват за 30 дней PVS-Studio 200,63 Рейтин..."
1,PVS-Studio,93 781 Подписчики,,"200,63 Рейтинг",,"64K+ Охват за 30 дней PVS-Studio 200,63 Рейтин..."
2,Veai,71 Подписчики,,"97,64 Рейтинг",,"64K+ Охват за 30 дней Veai 97,64 Рейтинг 71 По..."
3,NAUMEN,509 Подписчики,,"73,15 Рейтинг",,"8K+ Охват за 30 дней NAUMEN 73,15 Рейтинг 509 ..."
4,kino6052,Почему код становится legacy?,14K,31 авг 2023 в 16:01,"Блог компании билайн, Программирование*, Качес...","2K+ Охват за 30 дней билайн 60,12 Рейтинг 360 ..."
5,denis-19,Представлен проект «Мобильные JAVA игры в Tele...,15K,21 окт 2025 в 21:10,"Java*, Мессенджеры*, Игры и игровые консоли, Л...","Разработчик, популяризатор браузерного гейминг..."
6,MTCWebServices,Java&Kotlin-митап от MWS Cloud Platform в Казани,3.3K,3 сен 2025 в 13:00,"Блог компании MWS Cloud, Разработка публичных ...","32K+ Охват за 30 дней MWS Cloud 131,63 Рейтинг..."
7,vwisty,Приглашаем на Java-митап от Мир Plat.Form в Мо...,3.8K,25 ноя 2025 в 15:27,"Блог компании Мир Plat.Form (НСПК), Java*, Пла...",4K+ Охват за 30 дней Мир Plat.Form (НСПК) 114 ...
8,Vulkan,12K,,2 мин,,"Компания Mojang, создатель Minecraft, объявила..."
9,orionll,Вышла Java 25,44K,16 сен 2025 в 19:30,Java*,Вышла общедоступная версия Java 25. В этот рел...
10,alexbik,Статус Java 2026: помогаем собрать актуальную ...,,7 апр в 17:30,,"16K+ Охват за 30 дней Axiom JDK 116,79 Рейтинг..."
11,Samsung,38 733 Подписчики,,"64,54 Рейтинг",,"4K+ Охват за 30 дней Samsung 64,54 Рейтинг 38 ..."
12,4K,РЕКЛАМА,,"Блог компании ITFB Group, Криптография*, Postg...",,"8K+ Охват за 30 дней ITFB Group 43,1 Рейтинг 5..."
13,Samsung,38 733 Подписчики,,"64,54 Рейтинг",,"4K+ Охват за 30 дней Samsung 64,54 Рейтинг 38 ..."
14,ekhala,Вебинар «От кода до запуска: российский стек д...,,15 авг 2025 в 12:00,,"16K+ Охват за 30 дней Axiom JDK 116,79 Рейтинг..."
15,PVS-Studio,93 781 Подписчики,,"200,63 Рейтинг",,"64K+ Охват за 30 дней PVS-Studio 200,63 Рейтин..."
16,PVS-Studio,93 781 Подписчики,,"200,63 Рейтинг",,"64K+ Охват за 30 дней PVS-Studio 200,63 Рейтин..."
17,Haulmont,84 880 Подписчики,,"146,22 Рейтинг",,"64K+ Охват за 30 дней Haulmont 146,22 Рейтинг ..."
18,Haulmont,84 880 Подписчики,,"146,22 Рейтинг",,"64K+ Охват за 30 дней Haulmont 146,22 Рейтинг ..."
19,denis-19,Релиз Android-клавиатуры Unexpected Keyboard 2...,12K,5 мая в 07:30,"Android*, Java*, Смартфоны, Разработка мобильн...",В начале мая 2026 года состоялся релиз лёгкой ...
20,Maven,использовать bundled Maven для открытия проект...,,По моему мнению п.2 можно пропустить. Главное ...,,Всем привет. Недавно JetBrains выпустили в рел...
21,Haulmont,84 880 Подписчики,,"146,22 Рейтинг",,"64K+ Охват за 30 дней Haulmont 146,22 Рейтинг ..."
22,ekhala,Вебинар «Повышение безопасности приложений с п...,,26 фев в 17:10,,"16K+ Охват за 30 дней Axiom JDK 116,79 Рейтинг..."
23,mipo256,Поддержка Python и JavaScript в рамках Spring ...,6.6K,25 ноя 2025 в 20:05,"Блог компании Spring АйО, Программирование*, J...","32K+ Охват за 30 дней Spring АйО 73,94 Рейтинг..."
24,Haulmont,84 880 Подписчики,,"146,22 Рейтинг",,"64K+ Охват за 30 дней Haulmont 146,22 Рейтинг ..."
25,denis-19,GitHub опубликовал ежегодный статистический отчет,6.2K,3 дек 2020 в 10:40,"GitHub*, Open source*, Статистика в IT",В начале декабря 2020 года веб-сервис для хост...
26,petuhoff,Объектно ориентированное програмирование в гра...,,13 мая 2019 в 16:52,,Объектно-ориентированное программирование (ООП...
27,ekhala,Вебинар «Организация управления зависимостями в,,12 апр в 12:00,,"16K+ Охват за 30 дней Axiom JDK 116,79 Рейтинг..."
28,ekhala,Вебинар «Управляемые обновления и безопасная ц...,,13 мар в 14:20,,"16K+ Охват за 30 дней Axiom JDK 116,79 Рейтинг..."
29,Haulmont,84 880 Подписчики,,"146,22 Рейтинг",,"64K+ Охват за 30 дней Haulmont 146,22 Рейтинг ..."