# Импорт модулей

In [1]:
import pandas as pd

In [2]:
import requests

In [3]:
import json

In [4]:
from datetime import datetime

In [5]:
API_KEY = "QTDWSSW-P59M41D-K4HPD21-4YSPWW2"

In [6]:
BASE_URL = "https://api.poiskkino.dev"

In [7]:
headers = {
    "X-API-KEY": API_KEY,
    "accept": "application/json"
}

In [8]:
def get_movies(params=None):
    """
    page - страница
    limit - количество
    year - год/диапазон
    raiting.kp - рейтинг
    genres.name - жанр
    """
    url = f"{BASE_URL}/v1.4/movie"
    response = requests.get(url, headers=headers, params=params)
    if (response.status_code == 200):
        return response.json
    else:
        print(f"Ошибка при получении данных {response.status_code}")
        return None

# Работа с апи

In [9]:
params = {
    "page": 1,
    "limit": 250,
    "notNullFields": [
        "description",
        "name",
        "year", 
        "rating.kp",
        "genres.name"
    ]
}

In [10]:
data = get_movies(params)

In [11]:
df = pd.DataFrame(data()['docs'])

In [12]:
df.head()

,id,ageRating,alternativeName,backdrop,countries,description,genres,isSeries,name,poster,...,type,typeNumber,votes,year,names,movieLength,ratingMpaa,totalSeriesLength,status,logo
0,11921442,18.0,Snowball Earth,{'url': 'https://avatars.mds.yandex.net/get-ot...,[{'name': 'Япония'}],На Землю нападают пришельцы из космоса. Просто...,"[{'name': 'аниме'}, {'name': 'мультфильм'}, {'...",True,Земля-снежок,{'url': 'https://avatars.mds.yandex.net/get-ki...,...,anime,4,"{'kp': 230, 'imdb': 33}",2026,"[{'name': 'Snowball Earth', 'language': None, ...",NaN,NaN,NaN,NaN,NaN
1,11940727,18.0,Kami no Niwatsuki Kusunoki-tei,{'url': 'https://avatars.mds.yandex.net/get-ot...,[{'name': 'Япония'}],Семья поручила Минато Кусуноки присматривать з...,"[{'name': 'аниме'}, {'name': 'мультфильм'}, {'...",True,Божественный сад у поместья Кусуноки,{'url': 'https://avatars.mds.yandex.net/get-ki...,...,anime,4,"{'kp': 1897, 'imdb': 31}",2026,"[{'name': 'Kami no Niwatsuki Kusunoki-tei', 'l...",NaN,NaN,NaN,NaN,NaN
2,11979274,18.0,Паша Техник. За кем стоит андеграунд?,NaN,[{'name': 'Россия'}],История Паши Техника — от яркого представителя...,"[{'name': 'документальный'}, {'name': 'музыка'...",False,Паша Техник. За кем стоит андеграунд?,{'url': 'https://avatars.mds.yandex.net/get-ki...,...,movie,1,"{'kp': 329, 'russianFilmCritics': 4}",2026,[{'name': 'Паша Техник. За кем стоит андеграун...,90.0,NaN,NaN,NaN,NaN
3,342084,18.0,Hack-O-Lantern,NaN,[{'name': 'США'}],Ночь Хэллоуина никогда не была ещё столь крова...,[{'name': 'ужасы'}],False,Ночь Хэллоуина,{'url': 'https://avatars.mds.yandex.net/get-ki...,...,movie,1,"{'kp': 184, 'imdb': 2200}",1988,"[{'name': 'Ночь Хэллоуина', 'language': 'RU', ...",87.0,r,NaN,NaN,NaN
4,11095484,NaN,Slanted,NaN,[{'name': 'США'}],"С самого детства Джоан Хуан, дочь китайских ми...","[{'name': 'ужасы'}, {'name': 'фантастика'}, {'...",False,Раскосая,{'url': 'https://avatars.mds.yandex.net/get-ki...,...,movie,1,"{'kp': 543, 'imdb': 1584, 'filmCritics': 71}",2025,"[{'name': 'Slanted', 'language': None, 'type':...",104.0,r,NaN,NaN,NaN

In [13]:
df_noorm = df[['id', 'name', 'alternativeName', 'year', 'description', 'movieLength']].copy()

In [14]:
df_noorm['rairing'] = df['votes'].apply(lambda x: x.get('kp') if pd.notna(x) else None)

In [24]:
df_noorm['rating'] = df['rating'].apply(lambda x: x.get('kp') if pd.notna(x) else None)

In [25]:
df_noorm['genres'] = df['genres'].apply(
    lambda x: ', '.join([g['name'] for g in x]) if isinstance(x, list) else ''
)

In [26]:
df_noorm.head(250)

,id,name,alternativeName,year,description,movieLength,rairing,rating,genres
0,11921442,Земля-снежок,Snowball Earth,2026,На Землю нападают пришельцы из космоса. Просто...,NaN,230,7.568,"аниме, мультфильм, фантастика, приключения"
1,11940727,Божественный сад у поместья Кусуноки,Kami no Niwatsuki Kusunoki-tei,2026,Семья поручила Минато Кусуноки присматривать з...,NaN,1897,8.478,"аниме, мультфильм, фэнтези, драма, комедия"
2,11979274,Паша Техник. За кем стоит андеграунд?,Паша Техник. За кем стоит андеграунд?,2026,История Паши Техника — от яркого представителя...,90.0,329,7.181,"документальный, музыка, биография"
3,342084,Ночь Хэллоуина,Hack-O-Lantern,1988,Ночь Хэллоуина никогда не была ещё столь крова...,87.0,184,4.246,ужасы
4,11095484,Раскосая,Slanted,2025,"С самого детства Джоан Хуан, дочь китайских ми...",104.0,543,5.506,"ужасы, фантастика, драма, комедия"
...,...,...,...,...,...,...,...,...,...
245,477648,Хочу в Голливуд,Di Di Hollywood,2010,"История испанской золушки, вырвавшейся из бедн...",96.0,783,5.363,драма
246,477498,Винкс на концерте,Winx Club in concerto,2009,Это новое шоу с участием девушек из Winx Club....,3.0,1407,4.558,"мультфильм, детский, музыка, короткометражка"
247,477304,Игроки,Игроки,2005,"Шулер Ихарев, выигравший в карты восемьдесят т...",102.0,835,7.794,комедия
248,475462,Возродившийся машиной,Machined Reborn,2009,Молодой механик Кейд собирается открыть свое д...,80.0,181,3.104,ужасы
249,475307,Лига справедливости: Кризис двух миров,Justice League: Crisis on Two Earths,2009,"Лекс Лютор является из параллельного мира, что...",75.0,14847,7.072,"мультфильм, фантастика, фэнтези, боевик"

In [27]:
df_with_description = df_noorm[df_noorm['description'].notna() & (df_noorm['description'] != '')].copy()

In [28]:
df_with_description.head(250)

,id,name,alternativeName,year,description,movieLength,rairing,rating,genres
0,11921442,Земля-снежок,Snowball Earth,2026,На Землю нападают пришельцы из космоса. Просто...,NaN,230,7.568,"аниме, мультфильм, фантастика, приключения"
1,11940727,Божественный сад у поместья Кусуноки,Kami no Niwatsuki Kusunoki-tei,2026,Семья поручила Минато Кусуноки присматривать з...,NaN,1897,8.478,"аниме, мультфильм, фэнтези, драма, комедия"
2,11979274,Паша Техник. За кем стоит андеграунд?,Паша Техник. За кем стоит андеграунд?,2026,История Паши Техника — от яркого представителя...,90.0,329,7.181,"документальный, музыка, биография"
3,342084,Ночь Хэллоуина,Hack-O-Lantern,1988,Ночь Хэллоуина никогда не была ещё столь крова...,87.0,184,4.246,ужасы
4,11095484,Раскосая,Slanted,2025,"С самого детства Джоан Хуан, дочь китайских ми...",104.0,543,5.506,"ужасы, фантастика, драма, комедия"
...,...,...,...,...,...,...,...,...,...
245,477648,Хочу в Голливуд,Di Di Hollywood,2010,"История испанской золушки, вырвавшейся из бедн...",96.0,783,5.363,драма
246,477498,Винкс на концерте,Winx Club in concerto,2009,Это новое шоу с участием девушек из Winx Club....,3.0,1407,4.558,"мультфильм, детский, музыка, короткометражка"
247,477304,Игроки,Игроки,2005,"Шулер Ихарев, выигравший в карты восемьдесят т...",102.0,835,7.794,комедия
248,475462,Возродившийся машиной,Machined Reborn,2009,Молодой механик Кейд собирается открыть свое д...,80.0,181,3.104,ужасы
249,475307,Лига справедливости: Кризис двух миров,Justice League: Crisis on Two Earths,2009,"Лекс Лютор является из параллельного мира, что...",75.0,14847,7.072,"мультфильм, фантастика, фэнтези, боевик"

In [29]:
print(len(df_noorm))

250

In [30]:
print(len(df_with_description))

250

# Экспорт в CSV

In [31]:
df_noorm.to_csv('films.csv', index=False)

In [32]:
df_with_description.to_csv('films_with_desc.csv', index=False)