# Импорт модулей

In [1]:
import pandas as pd

In [2]:
import requests

In [3]:
import json

In [4]:
from datetime import datetime

In [5]:
API_KEY = "QTDWSSW-P59M41D-K4HPD21-4YSPWW2"

In [6]:
BASE_URL = "https://api.poiskkino.dev"

In [7]:
headers = {
    "X-API-KEY": API_KEY,
    "accept": "application/json"
}

In [8]:
def get_movies(params=None):
    """
    page - страница
    limit - количество
    year - год/диапазон
    raiting.kp - рейтинг
    genres.name - жанр
    """
    url = f"{BASE_URL}/v1.4/movie"
    response = requests.get(url, headers=headers, params=params)
    if (response.status_code == 200):
        return response.json
    else:
        print(f"Ошибка при получении данных {response.status_code}")
        return None

# Работа с апи

In [9]:
params = {
    "page": 1,
    "limit": 250,
    "notNullFields": [
        "description",
        "name",
        "year", 
        "rating.kp",
        "genres.name"
    ]
}

In [10]:
data = get_movies(params)

In [11]:
df = pd.DataFrame(data()['docs'])

In [12]:
df.head()

,id,ageRating,alternativeName,backdrop,countries,description,genres,isSeries,movieLength,name,...,typeNumber,votes,year,names,releaseYears,seriesLength,ratingMpaa,totalSeriesLength,status,logo
0,11887825,18.0,О чём на самом деле «Марти Великолепный»,{'url': 'https://avatars.mds.yandex.net/get-ot...,[{'name': 'Россия'}],"Редакция Кинопоиска разбирается, как устроена ...","[{'name': 'короткометражка'}, {'name': 'докуме...",False,10.0,О чём на самом деле «Марти Великолепный»,...,1,{'kp': 4561},2026,[{'name': 'О чём на самом деле «Марти Великоле...,NaN,NaN,NaN,NaN,NaN,NaN
1,12174541,NaN,Meurtres aux Marquises,{'previewUrl': 'https://avatars.mds.yandex.net...,"[{'name': 'Франция'}, {'name': 'Бельгия'}]","Тяжело переживая трагедию, из‑за которой ей пр...","[{'name': 'детектив'}, {'name': 'криминал'}]",False,94.0,Убийство на Маркизских островах,...,1,{'imdb': 28},2025,"[{'name': 'Убийство на Маркизских островах', '...",NaN,NaN,NaN,NaN,NaN,NaN
2,12095806,6.0,Космические котята,{'url': 'https://avatars.mds.yandex.net/get-ot...,[{'name': 'Россия'}],"В жизни Дениса Кукояки хватало съемок, приключ...","[{'name': 'документальный'}, {'name': 'коротко...",False,28.0,Космические котята,...,1,{'kp': 4553},2026,"[{'name': 'Космические котята', 'language': 'R...",NaN,NaN,NaN,NaN,NaN,NaN
3,11921442,18.0,Snowball Earth,{'url': 'https://avatars.mds.yandex.net/get-ot...,[{'name': 'Япония'}],На Землю нападают пришельцы из космоса. Просто...,"[{'name': 'аниме'}, {'name': 'мультфильм'}, {'...",True,NaN,Земля-снежок,...,4,"{'kp': 272, 'imdb': 33}",2026,"[{'name': 'Snowball Earth', 'language': None, ...",[{'start': 2026}],23.0,NaN,NaN,NaN,NaN
4,11940727,18.0,Kami no Niwatsuki Kusunoki-tei,{'url': 'https://avatars.mds.yandex.net/get-ot...,[{'name': 'Япония'}],Семья поручила Минато Кусуноки присматривать з...,"[{'name': 'аниме'}, {'name': 'мультфильм'}, {'...",True,NaN,Божественный сад у поместья Кусуноки,...,4,"{'kp': 3727, 'imdb': 31}",2026,"[{'name': 'Kami no Niwatsuki Kusunoki-tei', 'l...",[{'start': 2026}],23.0,NaN,NaN,NaN,NaN

In [13]:
df_noorm = df[['name','year', 'description', 'countries']].copy()

In [14]:
df_noorm['countries'] = df['countries'].apply(lambda x: x[0]['name'] if isinstance(x, list) and len(x) > 0 else None)

In [15]:
df_noorm['rating'] = df['rating'].apply(lambda x: x.get('kp') if pd.notna(x) else None)

In [16]:
df_noorm['genres'] = df['genres'].apply(
    lambda x: ', '.join([g['name'] for g in x]) if isinstance(x, list) else ''
)

In [17]:
df_noorm.head(250)

,name,year,description,countries,rating,genres
0,О чём на самом деле «Марти Великолепный»,2026,"Редакция Кинопоиска разбирается, как устроена ...",Россия,7.668,"короткометражка, документальный"
1,Убийство на Маркизских островах,2025,"Тяжело переживая трагедию, из‑за которой ей пр...",Франция,6.889,"детектив, криминал"
2,Космические котята,2026,"В жизни Дениса Кукояки хватало съемок, приключ...",Россия,7.382,"документальный, короткометражка, спорт"
3,Земля-снежок,2026,На Землю нападают пришельцы из космоса. Просто...,Япония,7.573,"аниме, мультфильм, фантастика, приключения"
4,Божественный сад у поместья Кусуноки,2026,Семья поручила Минато Кусуноки присматривать з...,Япония,8.490,"аниме, мультфильм, фэнтези, драма, комедия"
...,...,...,...,...,...,...
245,Правда о прививках,2006,Приводятся данные из документов для служебного...,Россия,6.258,документальный
246,Град,2010,"Осадки бывают разные, но этот больнее всех бьё...",Россия,5.413,"триллер, комедия"
247,Поединки: Вербовщик,2010,Даже на фоне других героев «невидимого фронта»...,Россия,7.082,"документальный, драма, история"
248,Тигровые глаза,2012,"После гибели отца в ходе ограбления Дэйви, ее ...",США,6.168,"драма, мелодрама, детектив, семейный"
249,Дети кукурузы: Генезис,2011,Сломав машину и застряв посреди калифорнийской...,США,3.254,"ужасы, триллер"

In [18]:
df_with_description = df_noorm[df_noorm['description'].notna() & (df_noorm['description'] != '')].copy()

In [19]:
df_with_description.head(250)

,name,year,description,countries,rating,genres
0,О чём на самом деле «Марти Великолепный»,2026,"Редакция Кинопоиска разбирается, как устроена ...",Россия,7.668,"короткометражка, документальный"
1,Убийство на Маркизских островах,2025,"Тяжело переживая трагедию, из‑за которой ей пр...",Франция,6.889,"детектив, криминал"
2,Космические котята,2026,"В жизни Дениса Кукояки хватало съемок, приключ...",Россия,7.382,"документальный, короткометражка, спорт"
3,Земля-снежок,2026,На Землю нападают пришельцы из космоса. Просто...,Япония,7.573,"аниме, мультфильм, фантастика, приключения"
4,Божественный сад у поместья Кусуноки,2026,Семья поручила Минато Кусуноки присматривать з...,Япония,8.490,"аниме, мультфильм, фэнтези, драма, комедия"
...,...,...,...,...,...,...
245,Правда о прививках,2006,Приводятся данные из документов для служебного...,Россия,6.258,документальный
246,Град,2010,"Осадки бывают разные, но этот больнее всех бьё...",Россия,5.413,"триллер, комедия"
247,Поединки: Вербовщик,2010,Даже на фоне других героев «невидимого фронта»...,Россия,7.082,"документальный, драма, история"
248,Тигровые глаза,2012,"После гибели отца в ходе ограбления Дэйви, ее ...",США,6.168,"драма, мелодрама, детектив, семейный"
249,Дети кукурузы: Генезис,2011,Сломав машину и застряв посреди калифорнийской...,США,3.254,"ужасы, триллер"

In [20]:
print(len(df_noorm))

250

In [21]:
print(len(df_with_description))

250

# Экспорт в CSV

In [25]:
df_noorm.to_csv('films.csv', index=False)